- cli.py
- lib/centralCLI/__init__.py
- lib/centralCLI/central.py
- lib/centralCLI/config.py
Reorg structure, adds Config object to parse config
add get_conn_from_file to get values from file and
set logical defaults for optional keys.
Add logging which squelches anything sent to display
> reorganize add logger add config parser and defaults

- cli.py
- lib/centralCLI/central.py
Add command option sites (to get all sites) and site_details (to get details on a single site). 
site list
```
cencli show sites --account multicare
address                              associated_device_count  city            country          latitude    longitude    site_id  site_name                                     state       tags      zipcode
---------------------------------  -------------------------  --------------  -------------  ----------  -----------  ---------  --------------------------------------------  ----------  ------  ---------
315 W Dalton Ave                                           1  Coeur d'Alene   United States     47.7231     -116.791        147  INW - Dalton Clinic (DALT)                    Idaho                   83815
2713 N Argonne Rd. …
```
> Add sites and site_details as command option

- config/config.yaml.example
Added comments that they can set the token_store and use account profiles.
> Minor update to config.yaml.example

- cli.py
- config/config.yaml.example
- lib/centralCLI/utils.py
ARUBACLI_ACCOUNT=<account profile>
ARUBACLI_DEBUG=1
> Use os environment var to setup DEBUG and ACCOUNT

- .vscode/launch.json
- cli.py
- devcli.py
- lib/centralCLI/central.py
- lib/centralCLI/config.py
- lib/centralCLI/constants.py
- lib/centralCLI/utils.py
- out/.gitignore
pretty major rewrite in a lot of places.
help text looks pretty good.  There is an optional 2nd argument with variable length
help text concisely displays arguments vs gateway[s] vs gateway|gateways... 
file output support.  Probably broke some stuff but wanted to get it merged to avoid merge conflicts
> refactor show, file output, more filter options

- cli.py
- lib/centralCLI/central.py
`cencli method-test bounce_poe port=5 serial_num=CN71HKZ1CL`
anything after the method without = is passed as a positional arg
stuff separated by = gets passed as kwarg
+ refactor the post methods to pycentral.
> convenience func to test methods in CentralAPI (central.py) from cli

- .vscode/launch.json
- centralCLI/__init__.py
- centralCLI/central.py
- centralCLI/constants.py
- centralCLI/utils.py
- cli.py
Colorized Status Up/Down for show <device>
Added show all support using new method
built support for all the available filtering options i.e.
`show all --label Branch_View --status up`
bounce PoE and interface `cencli method-test bounce_poe 6 <serial>`  need to use method-test until we have a command hierarchy for it.
> show <device> method chg bounce_poe... output tweaks

- .vscode/launch.json
- centralCLI/__init__.py
- centralCLI/central.py
- centralCLI/constants.py
- cli.py
`do bounce-interface <port> --serial aabbcc`
`do bounce-poe <port> --serial aabbcc`
`show all`, `show <device type> [filters: --label, --model, --etc]
> Show command updates, add action `do` commands

- centralCLI/__init__.py
- centralCLI/central.py
- centralCLI/constants.py
- centralCLI/utils.py
- cli.py
Previous merge moved data cleaning from cli.py inside the various functions
to Response object.  Inconsistent outer dict key is now stripped in response
This messed up some of the methods that where expecting the outer key
> fix methods to handle change in where data is cleaned +clean show sites output

- centralcli/central.py
- centralcli/cli.py
- centralcli/constants.py
- centralcli/response.py
- tests/test_do.py
Move device to a different group
> add `do move <dev identifier> <group identifier>`

- centralcli/central.py
- centralcli/cli.py
central.py + 2 methods to initiate a snapshot on a group, and list all snapshots for a group.
cli.eval_resp() updated to use keys in aiohttp.Response() when error occurs.
> Add group snapshot methods, tweak method-test output, update evel_resp()

- centralcli/cache.py
- centralcli/cli.py
- centralcli/response.py
New logic in get_dev_identifier had to be tweaked for the flow in show templates
> Fix show templates by name

- centralcli/cache.py
- centralcli/central.py
- centralcli/cli.py
- centralcli/config.py
- centralcli/response.py
More details in the individual commits
> Add Unique cache.db for each --account

- centralcli/allcalls.py
- centralcli/central.py
- centralcli/cleaner.py
- centralcli/cli.py
- centralcli/configuration.py
- centralcli/constants.py
- centralcli/firmware.py
- centralcli/guest.py
- centralcli/response.py
- centralcli/wlan.py
allcalls.py is what's left of original generated code
after pulling portions out into the other files
allcalls.py will bog down ide given size so needs to be broken out.
Right now the calls that are actually used by the CLI are all in central.py
> +show logs, + generated methods, [fix] paged output.

- centralcli/central.py
- centralcli/cleaner.py
- centralcli/cli.py
- centralcli/constants.py
- centralcli/utils.py
test with `--rich` for output.  In a lot of outputs this is a better view.  It gives us a lot of options.
> rich formatter, fix cols order in show all

- centralcli/cache.py
- centralcli/central.py
- centralcli/cleaner.py
- centralcli/cli.py
- centralcli/config.py
- centralcli/response.py
- centralcli/utils.py
- centralcli/vscodeargs.py
- requirements.txt
With import file something like this.
```csv
site_name,address,city,state,zipcode,country
delme13,820 Barry Ln,Gallatin,TN,37066,USA
delme14,,Memphis,TN,,USA
delme15,,Dallas,TX,,USA
```
> `batch path/file.csv`  batch create sites.  cmd will be built out properly l8r.

- .gitignore
- centralcli/allcalls.py
- centralcli/cache.py
- centralcli/central.py
- centralcli/cleaner.py
- centralcli/cli.py
- centralcli/clishow.py
- centralcli/constants.py
- centralcli/utils.py
- tests/test_devices.json.example
- tests/test_do.py
- tests/test_show.py
This is not 100% complete, but pretty close re breaking out show.
Given the eventual complexity/levels of the command tree, figured would be good to get my head around this now.
This has the benefit of making the help context more specific to the place in the tree
show variables, certs, clients, logs have yet to be completed.  All other show commands should work.
> modularize command structure - phase 1 - breakout show

- centralcli/central.py
- centralcli/clibatch.py
- centralcli/clishow.py
- centralcli/config.py
- centralcli/constants.py
- centralcli/utils.py
Add:
`cencli batch rename aps --lldp`
`cencli show config`
> cencli batch renamp aps --lldp

- centralcli/boilerplate/allcalls.py
- centralcli/central.py
- centralcli/cli.py
- centralcli/clibatch.py
- centralcli/clidel.py
- centralcli/clido.py
- centralcli/constants.py
- centralcli/response.py
- pyproject.toml
Adds:
`cencli batch delete sites /path/file`
`cencli delete certificate <name>`
`cencli delete site <name|id|address...>`
> add batch delete, cencli delete as 2nd level

- centralcli/constants.py
- pyproject.toml
Adding swarms to strip keys jacked show all
> fix cli show all, reorder strip keys.

- centralcli/cache.py
- centralcli/cleaner.py
- centralcli/clicommon.py
- centralcli/clishow.py
- centralcli/constants.py
- centralcli/utils.py
- pyproject.toml
- tests/test_show.py
see commit msgs for details.
All tests pass
> show clients and show logs enhancements

- centralcli/cache.py
- centralcli/clibatch.py
- centralcli/clicommon.py
- centralcli/clidel.py
- centralcli/response.py
- tests/test_add.py
- tests/test_batch.py
- tests/test_del.py
- tests/test_do.py
don't have 100% coverage on all commands yet
> batch improvements, cencli delete sites improvement

- centralcli/cache.py
- centralcli/central.py
- centralcli/cli.py
- centralcli/clido.py
- centralcli/constants.py
- pyproject.toml
PLUS: if it works auto-completion for groups / devices.  Testing package version.
More detail in commit msgs.
> `cencli move <dev> ... site <site> group <group>`

- centralcli/central.py
- centralcli/clishow.py
- pyproject.toml
`cencli show upgrade <dev>` or `cencli show upgrade status <dev>`
> Show Upgrade status

- centralcli/__init__.py
- centralcli/cache.py
- centralcli/central.py
- centralcli/cli.py
- centralcli/clicommon.py
- centralcli/clido.py
- centralcli/clishow.py
- centralcli/config.py
- centralcli/constants.py
- pyproject.toml
Likely would still be an issue if no config file exists at all...
verify/fix that scenario soon
> fix: --account -d / auto completion

- centralcli/__init__.py
- centralcli/cache.py
- centralcli/clicommon.py
- centralcli/config.py
- centralcli/constants.py
- pyproject.toml
--account completion only implemented at root level
`cencli --account [tab][tab]` 
will implement further after verified
Fix missing alias translations for cli upgrade
> completion for accounts, add common alias translations

- centralcli/cache.py
- centralcli/central.py
- centralcli/cli.py
- centralcli/clicommon.py
- centralcli/clido.py
- centralcli/clishow.py
- centralcli/cliupgrade.py
- centralcli/constants.py
- centralcli/utils.py
- pyproject.toml
`cencli move` will now remove from existing site if already associated prior to moving to specified site.
Number of output tweaks in clishow
> --sort / --reverse support for most show cmds, new remove <dev> .. <site>

- centralcli/boilerplate/configuration.py
- centralcli/cache.py
dev_kwarg_completion returns filtered completion i.e. if last arg was gateways then completion will only return matching gateways.
> fix completion in dev_kwarg_completion

- centralcli/cache.py
- centralcli/central.py
- centralcli/cliadd.py
- centralcli/constants.py
- pyproject.toml
`cencli add device serial CNABCSERIAL mac '20:4c:03:aa:bb:cc' group WLNET --license advanced_ap`
Minimum Required: `cencli add device serial CNABCSERIAL mac '20:4c:03:aa:bb:cc'`
group and license are optional (each results in an additional API call)
API calls are batch.  device is added then the other 2 run async.
> version 0.10a35 ~ cencli add device (group/license optional)

- .vscode/settings.json
- centralcli/boilerplate/allcalls.py
- centralcli/boilerplate/configuration.py
- centralcli/caas.py
- centralcli/cache.py
- centralcli/central.py
- centralcli/cleaner.py
- centralcli/cli.py
- centralcli/clishow.py
- centralcli/cliupdate.py
- centralcli/constants.py
- centralcli/response.py
- pyproject.toml
New command `show dhcp <server|clients> <device(gw only)>`
enhanced command 'show interfaces <device>` where device can now be a gw
completion fixes, caas... see commit log for further details
> Central 2.5.4 updates, show dhcp ..., show interfaces (for gws), completion fixes

- centralcli/cache.py
- centralcli/central.py
- centralcli/config.py
- centralcli/constants.py
Will need to look at this further when imports/inheritance is reviewed.
> skip pycentral load when not needed

- README.md
- centralcli/central.py
- centralcli/cleaner.py
- centralcli/clishow.py
- centralcli/response.py
- centralcli/utils.py
- docs/centralcli.rst
- docs/conf.py
- docs/index.rst
- docs/modules.rst
- docs/requirements.txt
- pyproject.toml
Add underlying module documentation
> Expand Documentation

- centralcli/central.py
- centralcli/cleaner.py
- centralcli/clicommon.py
- centralcli/clishow.py
- centralcli/config.py
- centralcli/response.py
- centralcli/utils.py
- config/config.yaml.example
- pyproject.toml
See commit history some other minor stuff as well.
> Add First Run (Configuration) Wizard

- centralcli/clishow.py
- pyproject.toml
for real this time ... faster than cleaning the commits up.
> [fix] show events --dev-type option

- centralcli/clirefresh.py
merging to trigger cli docs update
> remove unnecessary module level help text

- centralcli/cache.py
- centralcli/cli.py
- centralcli/cliadd.py
- pyproject.toml
only impactful change is fixing an issue with unassign (license)
> v0.22.6 minor update

- centralcli/cleaner.py
- centralcli/clibatch.py
- pyproject.toml
Import hell was injected with prev release... Fixed
> v0.23.2 Break Fix release.  Would fail after install

- centralcli/cache.py
- centralcli/central.py
- centralcli/clibatch.py
- centralcli/cliupdate.py
- centralcli/config.py
- centralcli/response.py
- centralcli/wh_proxy.py
- pyproject.toml
- 🐛 fix batch move sites
- ✨ use gateways endpoint for dhcp calls only use mobility_controllers path if cop
- 🐛 fix list expansion in  in print statement
> 🔖 v2.3.13 🐛 fixes

- centralcli/cache.py
- centralcli/clibatch.py
- centralcli/clicaas.py
- pyproject.toml
- tests/test_show.py
- :ambulance: Fix `cencli show config`  Broken in previous release
- :white_check_mark: Add tests for `cencli show config`
- :bug: Fix completion in hidden command `cencli caas send-cmds`
- :speech_balloon: Improve batch move help text
> :ambulance: :bookmark: v4.0.1

- requirements.txt
Probably won't work, but don't want to remove it from pyproject.toml as it would break completion.
> :poop: try removing click pin from just requirements.txt

- centralcli/cache.py
- centralcli/central.py
- centralcli/cleaner.py
- centralcli/clishow.py
- centralcli/cliupdate.py
- centralcli/logger.py
- centralcli/models.py
- centralcli/response.py
- pyproject.toml
- :ambulance: Fix issue where partial failure in `show all` would result in unexpected output.
- :speech_balloon: Make help text color consistent with others
- :bug: logger: fix issue where `show` parameter was not being honored
- :speech_balloon: include uptime in show device commands but round to nearest min to save horizontal space
> :bookmark: v6.0.1

- README.md
- centralcli/clishowospf.py
- centralcli/config.py
- centralcli/logger.py
- centralcli/response.py
- centralcli/utils.py
- centralcli/wh2snow.py
- pyproject.toml
- tests/test_show.py
- :ambulance: fix compat with python <= 3.9.  correct missing "from __future__ import annotations"
- :memo: Update required python to 3.8 + other updates to README
- :wrench: Add uswest5 url to CLUSTER_URLS for first run wizard
> :bookmark: v6.3.1

- README.md
- centralcli/__init__.py
- centralcli/clishow.py
- centralcli/clishowbandwidth.py
- centralcli/constants.py
- centralcli/render.py
- centralcli/wh_proxy.py
- pyproject.toml
- :sparkles: Add support for filtering clients by band
- :memo: update import formats, swap emoji for literal emoji.
- :memo: add package documentation / docstr
> :bookmark: v6.4.0

- centralcli/cache.py
- centralcli/clishow.py
- pyproject.toml
- :sparkles: Add per band counts to client caption
- :card_file_box: revert client cache update to only truncate if told to.
- :sparkles: catch errant use of filters for show clients without sending an API call
- :zap: Improve client cache update speed
> :bookmark: v6.4.1

- centralcli/cache.py
- centralcli/clishow.py
- pyproject.toml
- :ambulance: Convert TinyDB docs to dict in Cache properties to avoid conflict with doc_id when combining/updating
- :speech_balloon: Use name from cache vs name from input in show clients title
> :bookmark: v6.4.2
