Pack3tL0ss/central-api-cli

.gitignore, cli.py, lib/centralCLI/central.py
This PR adds the ability to have multiple Aruba Central accounts in the config.yaml file. You can then pass the --account <acount_name> options and it will then query against the account. If --account is not set, it will default to central_info; which will not break any existing config.yaml configurations.
This requires the `session = _refresh_tokens(account)` to be added to all existing and future app.commands() as it no longer runs before app.command. I've only added this def show() as I have not used the other app.commands() yet. 
`python3 cli.py show ap` 
Will show the APs from the account central_info
`python3 cli.py show ap --account sephora`
Will show the APs from the account sephora
Example config.yaml file.
`{
"central_info": {
"base_url": …
=> Added the ability to pass an account name to switch from different Aruba Central accounts

cli.py, lib/centralCLI/utils.py, requirements.txt
JSON output
`cencli show ap --account sephora -j`
Formatted table defaulted to "simple"
`cencli show ap --account sephora`
Another format available
`cencli show ap --account sephora --output psql`
`cencli show ap --account sephora --output fancy_grid`
`cencli show ap --account sephora --output html`
Other formats:
"plain"
"simple"
"github"
"grid"
"fancy_grid"
"pipe"
"orgtbl"
"jira"
"presto"
"pretty"
"psql"
"rst"
"mediawiki"
"moinmoin"
"youtrack"
"html"
"latex"
"latex_raw"
"latex_booktabs"
"textile"
=> CLI output: Display content in a json or ASCII table with different formats

.vscode/launch.json, .vscode/launch.json.bak, .vscode/tasks.json, cli.py, lib/centralCLI/__init__.py, lib/centralCLI/central.py, lib/centralCLI/constants.py, lib/centralCLI/utils.py
can now address dict key as Response class attribute
resp["output"]["site"] available via resp["site"] and resp.site
Also works for 2nd level of output dict if 2nd level is a dict
Also (from prev commit)
```
if resp:
returns a bool (resp.ok)
```
and `print(resp)` prints contents of self.output (the dict)
=> vscode debugger args work-around. Response object enhancements, output tweak

centralCLI/config.py, cli.py, requirements.txt
Adds support for using friendly identifiers.  When launched if no cache exist or the local cache is > 2 hours old all devices and all sites will be collected in the background and stored locally.
This facilitates i.e. to show the template for a specific device: `show template 10.0.30.224`, or `show template bsmt-2930F` *and* `show template <serial-num>` vs just allowing by serial-num.
Instantiated: cache = Identifiers(session)
Then `_args = cache.get_dev_identifier(args)` will look for a match by name ip serial or mac and return the serial of any devices that match.  Currently returns the fist match in the event of multiple.  Plan is to return all matches and output for things like show commands, and display matches with an ambiguous error or confirmation for `do` actions.
Also likely …
=> Adds Caching and friendly identifier support

centralCLI/utils.py, cli.py
All should now work:
```
cencli show template BSMT-2930F  # case insensitive name of switch
cencli show template cn99abc1cl    # case insensitive serial
cencli do bounce-poe bsmt-2930f 2 -Y  # case insensitive device name with -Y option (will prompt for confirmation without -Y)
cencli do bounce-poe 10.0.30.5 2 -Y      # same but by ip
cencli do bounce-poe aabbcc-ddeeff 2 -Y # same but by mac (any format)
cencli do bounce-interface BSMT-2930f 2 -Y  # bounce interface by switch name
#
cencli show site Antigua
cencli show sites 12610 antigua dr
cencli show sites Noblesville
cencli show sites 10
cencli show sites Indiana
cencli show sites 46060
```
In general 
- Matching fields checked for *devices:* name, ip, mac, serial *sites:* name, site_id, zipcode, address, city, state
- we try case …
=> extend friendly identifier support to `show sites` and do commands

centralCLI/__init__.py, centralCLI/central.py, centralCLI/utils.py, cli.py
`cencli template ... ` commands work .. update anyway
`cencli template update ...`
tokens are only refreshed as needed after initial call fails due to expired token
similar to what pycentral does natively but with support for internal only token only refresh
internal user is prompted to paste contents of "Download Template" from central ui
=> refresh token with internal (token only) refresh support ++

centralCLI/__init__.py, centralCLI/central.py, centralCLI/constants.py, centralCLI/utils.py, cli.py
Add show_dev_details `show switch idf1-sw2` ... Only tested with switch so far, but may work for others
Handle ArubaCentralBase trying to exit when no token
If the token is invalid and there is no token block in the config
user will be given opp to paste entire json from `Download Token`  in UI
=> Auto-Refresh Token with user-input should be good

centralcli/cache.py, pyproject.toml
minor refactor to avoid getting all group details from central twice during cache update
=> make update_cache more efficient

centralcli/cache.py, centralcli/cleaner.py
Will now attempt to find matches replacing - with _ and visa versa
Then will look for matches that start with the provided id.
If multiple devices match user is prompted to select from the resulting match
**NOTE: Still need to re-factor the query**
dev_identifier doesn't factor in the dev type so ...
`show switch bsmt-` could return an AP with a name that starts with `bsmt-`
=> tweak get_dev_identifier() more matching options. Multi-dev select

centralcli/cache.py, centralcli/cleaner.py, centralcli/cli.py, centralcli/config.py, centralcli/utils.py
`--account` is now sticky.  `-d` can be used as shorthand to return to default account.
By default it's sticky forever, but 
` forget_account_after: 30` can be set in the config, then the account will return to default 30 mins after last command.
more work with rich library.  it will fit output to tty size automatically and fold or ... the output in the col, still needs more work, but looks promising.
Also all device outputs, not strip all cols that have no value (or `Unknown`) for all devices.
=> sticky account name, and lots of formatting work

centralcli/cache.py, centralcli/cleaner.py
cache update methods fix from last commit was lacking assignment back to the variable, do didn't fix anything.  This should
conditional in cleaner.strip_no_value() when a single empty list is the result of no_val comprehension.
=> [fix] cache update methods, and cleaner.strip_no_value()

centralcli/__init__.py, centralcli/cleaner.py, centralcli/clishow.py, centralcli/config.py, centralcli/utils.py, pyproject.toml
Found on windows with pypi install that
typer.get_app_dir(__name__) returned the full path
in site_packages, not what we want.
program now looks for config in a number of places:
```
[
Path().home() / ".config" / "centralcli",
Path().home() / ".centralcli",
cwd / "config",
cwd,
Path().home() / ".config" / "centralcli" / "config",
]
```
If the config file is in any of those then that's what is
used, and directory structure is derived from there.
=> Change config dir location logic.

centralcli/config.py, pyproject.toml
Update after testing last merge, still needed minor tweak.
will now default to `%HOME%\.centralcli` for Windows.
if typer.get_config_dir() yileds package directory.
Technically for any OS, but typer.get_config_dir() returns a logical value for *nix based systems
`~/.config/centralcli on linux`
=> fix Windows config_dir

.vscode/settings.json, README.md, centralcli/__init__.py, centralcli/caas.py, centralcli/cache.py, centralcli/central.py, centralcli/cli.py, centralcli/clibatch.py, centralcli/clicaas.py, centralcli/clicommon.py, centralcli/clido.py, centralcli/clishow.py, centralcli/response.py, pyproject.toml
refactor some name-spaces, create clicommon w/ CLICommon object...
CentralApi where all the actual API calls are... chgd from session -> central
ArubaCentralBase goes session.central -> central.auth
Both of the above should be derived from the new CLICommon class available as `cli` from __init__
cli.central:  Where all the API methods live
cli.central.auth:  ArubaCentralBase class
cli.cache common cache object now available to all files (just import cli)
callbacks and output methods are all under cli
cli.account_name_callback, cli.eval_resp...
=> Build Out ReadMe, re-factor namespaces, common cli object

centralcli/cache.py, centralcli/response.py
spinner instance was running during get_token_from_user prompt
Also had multiples running flipping the req_count back and forth.
Same spinner instance is used for all spinners now.
=> fix: adjust spinner

centralcli/clibatch.py, centralcli/clicommon.py
Not sure how it was working before but it was.  I listify response
as if I was potentially expecting a list of Response objects.
But the command to get aps (line 36) is not a batch, so would only
expect a single Response (with a list of dicts in output attribute).
Need to add per site / per ap filters.
=> fix: auto rename based on lldp

centralcli/__init__.py, centralcli/boilerplate/configuration.py, centralcli/clibatch.py, centralcli/clicommon.py, centralcli/response.py, pyproject.toml
Now handles int specifiers > 1 digit i.e. `%h[5:10]`
Add format string validation and error detection
w/ verbose messaging for detected errors.
Loop for retry if errors.
Still needs to be simplified, Readability a bit on the meh side, but
functional.
=> improve: batch rename APs

centralcli/central.py, centralcli/clishow.py
`show groups -v` will add AoSVersion (8x/10x) and MonitorOnlySwitch
columns to output (additional API call to central to gather)
=> feature: Add `-v` option to show groups.

centralcli/boilerplate/firmware.py, centralcli/cache.py, centralcli/central.py, centralcli/cli.py, centralcli/cliadd.py, centralcli/cliclone.py, centralcli/clidel.py, centralcli/clido.py, centralcli/cliupgrade.py, centralcli/constants.py, centralcli/vscodeargs.py, pyproject.toml
`cencli add group test1 myP@ssw0rd`
```
cencli add group test1
Group Password: -masked-
Re-Enter to Confirm: -masked-
Add group test1? [y/N]: Y
created
```
`--wired-tg`  and `--wlan-tg` options supported
This commits enhances cache to allow cache to be updated with a single group entry vs. a full cache update.  After add group, the group added is added to the cache.
Also cone group, and delete group.  Delete group allows multiple group entries
```
cencli delete group test1 test2 test3
```
=> + add / clone / delete group.  upgrade (firmware)

centralcli/cache.py, centralcli/clicommon.py, centralcli/clishow.py, centralcli/config.py, centralcli/constants.py, centralcli/utils.py
`show last` will re-display the result of the last command
(non action command).
Previous command can be repeated with `show last`.
Output format / sorting and output to file option can be chosen.
This allows re-display in alternate formats, or the same format
without actually performing the same API call again.
=> Add `show last`

centralcli/cli.py, centralcli/cliassign.py, centralcli/cliunassign.py, centralcli/constants.py, pyproject.toml
:sparkles: Add commands to show/disable/enable auto-subscription
:bug: The enable/disable commands are currently hidden. As GreenLake and the API have some inconsistencies.
auto-sub advanced-switch-6300 will result in the API showing it is
enabled for all switches (this is OK).   However GreenLake doesn't reflect
the change.  The API to disable unsubscribe will return OK, but doesn't appear
to change anything.  The only way to get the API (that shows what is enabled)
to clear auto-sub is to create then delete auto-sub from GreenLake UI.
=> :bookmark: v2.3.3

centralcli/clicaas.py, centralcli/clishow.py, centralcli/render.py, pyproject.toml
- :speech_balloon: Improve styling of error messages in `show config` 
- :speech_balloon: Fix color styling of `caas send-cmds` output     
- :construction:  When commands are sent to multiple gateways output currently does not indicate which output is for which
=> :bookmark: v4.0.2

docs/requirements.txt
read-the-docs build process was installing a very old version of uvicorn with a known issue.
=> :pushpin: pin everything in doc requirements

docs/requirements.txt
typer is installing typer-slim which has a different click dep
click pin is for the sake of completion, which shouldn't impact docs build
=> :poop: remove click pin for docs

centralcli/central.py, centralcli/cleaner.py, centralcli/cli.py, centralcli/clicommon.py, centralcli/clishow.py, centralcli/constants.py, centralcli/logger.py, centralcli/objects.py, centralcli/render.py, centralcli/utils.py, pyproject.toml
- :sparkles: Overhaul `cencli show clients` Now supports more filtering options.
-  :sparkles: Extensive improvements to verbose output format
- :sparkles: proper sorting on last_connected field
-   :sparkles: throughput/usage converted to human readable
- :sparkles: `cencli show tunnels` gets cleaner which makes date fields and data usage/throughput fields human readable
- :label: Add sort Enum for Client Time Range, and Literal type for ClientStatus
- :technologist: Change default for log methods, when caption=True, it will not log to file unless log=True.  By default caption is False and it will log to file.
- :coffin: Remove unused code
- :technologist: Add helper to convert int/float output representing data bytes to human readable
- :speech_balloon: Handle emoji in log.caption
- …
=> :bookmark: v5.4.0

centralcli/cache.py, centralcli/central.py, centralcli/clibatch.py, centralcli/response.py, pyproject.toml
- :bug: prevent potential reference before assignment if all calls Failed in response.CombinedResp.flatten_resp
- :bug: return expected number of Response objects in _check_fresh even if aborting after 1st update fails.
- Make dev_type None equiv to dev_type="all" (in call to fetch inventory)
- :loud_sound: Put try/except around log message verifying total and count add up
- :bug: fix flaw in logic impacting CoP delete in `batch delete devices`
=> :bookmark: v6.1.1

centralcli/boilerplate/allcalls.py, centralcli/cache.py, centralcli/central.py, centralcli/clicommon.py, centralcli/clishowaudit.py, centralcli/clishowbandwidth.py, centralcli/response.py, pyproject.toml
- :sparkles: `cencli show audit logs` now shows the audit event logs.  `cencli show audit system-logs` show audit logs.  `show audit logs` is generally more useful.
- :sparkles: Response: improve handling of count parameter
- :bug: minor fix in _verify_time_range
- :speech_balloon: Only colorize green/red top of "action" response, not entire response.  So rich can colorize body.
- :sparkles: improve cache.get_log_identifier
- :sparkles: update central.get_audit_logs_events
=> :bookmark: v6.2.0

centralcli/cache.py, centralcli/central.py, centralcli/cliassign.py, centralcli/clibatch.py, centralcli/clidel.py, centralcli/clishowaudit.py, centralcli/clishowbandwidth.py, centralcli/clitest.py, pyproject.toml, tests/test_batch.py
- :sparkles: Add bandwidth usage for wlan/ssid `cencli show bandwidth wlan <wlan>`
- :speech_balloon: Improve error msg / spinner when cache update has partial failure
- :technologist: Allow List of group names for get_all_templates
- :sparkles: allow friendly dev iden for `cencli assign license` (useful if you remvoe/re-add subscription)
- :zap: improve smg_kw_completion
- :coffin: clean up commented code from lldp refactor
- :card_file_box: cache update after auto rename by LLDP
- :recycle: do_lldp_rename is now get_lldp_names and returns dictionary
- Actual calls are parsed by the same logic as if the data were pulled from an import file.  So gets same cache update treatment
- :bug: Fix bug in lldp rename when using %h[1-4] (h could be anything valid) in format string.
- …
=> :bookmark: v6.3.0

centralcli/cache.py, pyproject.toml
- :ambulance: hotfix to avoid exception during cache update when no devices exist in Central yet.
=> :bookmark: v7.2.1

centralcli/cache.py, pyproject.toml, tests/test_batch.py
- :rewind: revert part of client completion change.  Needs to be here for empty `incomplete`, zsh doesn't like the colons.
- :sparkles: help_text for portal completion
- :white_check_mark: Change success test for batch add groups test
=> :bookmark: v7.2.3

centralcli/cache.py, centralcli/cleaner.py, centralcli/clicommon.py, centralcli/clikick.py, centralcli/clishow.py, centralcli/clitest.py, centralcli/models.py, centralcli/response.py, centralcli/strings.py, pyproject.toml
- :sparkles: Add `cencli show cron`
- :bug: fix issue where interface cleaner was stripping out speed on switches.
- :bug: fix bug when -R is specified
- :sparkles: verify individual client if cache indicates client is offline.  Better error msg when that occurs.
- :bug: resolve validation error in pydantic model with None for last_connected (failed client)
- :bug: fix potential double cache update when dev_type passed to get_dev_identifier
- :speech_balloon: Improve show <DEV TYPE> caption when --up / --down flag is used,.
- :sparkles: Add portal comletion for `show guests`
- :bug: fix exception building caption when wlan name is provided
- :art: improve colorized output
- :goal_net: catch and show error if --out directory does not exist.
=> :bookmark: v7.2.4
